### PR TITLE
Kotlin Multiplatform compatibility and project structure upgrade

### PR DESCRIPTION
**Pull request by sergeych**
I've replaced java Pattern with Kotlin Regex (hopefully in a correct way, at least test looks good). I have also change the project structure to current requirements (the original version didn't build now).

### CODE REVIEW

**Comment by marcelmatula** [comment]
some gradle setting is missing. When I clone clean project i am getting:

org.gradle.internal.exceptions.LocationAwareException: Build file 'xxxxx/colored-console-fork/build.gradle.kts' line: 2
Script compilation error:

  Line 2:     alias(libs.plugins.kotlinMultiplatform)
                    ^ Unresolved reference: libs

**Comment by sergeych** [comment]
oops, sorry, just added.

**Comment by sergeych** [comment]
Any other objections?

**Comment by marcelmatula** [comment]
@sergeych merged

**Pull request merged**
